### ISSUE TITLE
easyCredit-Ratenkauf: A technical error occurred during the integration of ratenkauf by easyCredit. Please contact the web shop.

### ISSUE THREAD

**Issue by magento360** [teambank/ratenkaufbyeasycredit-plugin-magento-2#10]
We are getting issues with latest version:  "1.3.10",
Es ist ein technischer Fehler bei der Integration von ratenkauf by easyCredit aufgetreten. Bitte kontaktieren Sie den Webshop.
                    [details] => Can not construct instance of de.easycredit.ratenkauf.ws.v2.model.speichern.Anrede from String value '': value not one of declared Enum instance names

**Comment by netzkollektiv** [comment]
Providing a customer prefix ("Anrede") is mandatory for the payment initialization. In your case the prefix value seems to be empty. Either make sure that customers are able to select a prefix in the checkout or during payment selection or install the latest version of the extension ([v2.0.3](https://github.com/teambank/ratenkaufbyeasycredit-plugin-magento-2/releases/tag/2.0.3)) which is using a newer API version, where the prefix is not required anymore.
