### ISSUE TITLE
Order missing on magento

### ISSUE THREAD

**Issue by magento360** [teambank/ratenkaufbyeasycredit-plugin-magento-2#11]
Order is recorded at easycredit store but order is not created at magento admin , there is no such entry with order_id that is created on easycredit store.
I have just installed latest version: 2.0.3

The order_id (**10000183981**) which is missing on magento but recorded on easycredit store.
Log:
[2023-03-13 12:17:52] Netzkollektiv_EasyCredit.DEBUG: get(duration) =>  [] []
[2023-03-13 12:17:52] Netzkollektiv_EasyCredit.DEBUG: get(sec_token) => ***** [] []
[2023-03-13 12:17:52] Netzkollektiv_EasyCredit.DEBUG: get(sec_token) => **** [] []
[2023-03-13 12:17:52] Netzkollektiv_EasyCredit.DEBUG: get(authorized_amount) => 3134.9900 [] []
[2023-03-13 12:17:52] Netzkollektiv_EasyCredit.DEBUG: get(interest_amount) => 0 [] []
[2023-03-13 12:17:52] Netzkollektiv_EasyCredit.DEBUG: get(address_hash) => ******* [] []
[2023-03-13 12:17:52] Netzkollektiv_EasyCredit.DEBUG: get(token) => **** [] []
[2023-03-13 12:17:53] Netzkollektiv_EasyCredit.DEBUG: "POST https://ratenkauf.easycredit.de/api/payment/v3/transaction/*******/authorization HTTP/1.1" 202 Accepted [] []
[2023-03-13 12:17:53] Netzkollektiv_EasyCredit.DEBUG: >>>>>>>>
{"orderId":"**10000183981**"}
<<<<<<<<

**Comment by netzkollektiv** [comment]
The easyCredit-Ratenkauf extension implements the default payment behavior by extending from \Magento\Payment\Model\Method\AbstractMethod. The order is not created by the extension but rather by Magento itself. Please check the relevant logs for any errors (debug.log, exception.log, payment.log). Please check for third-party extensions affecting order creation. Please also reference to https://github.com/magento/magento2/issues/25550 to see what likely went wrong.

**Comment by p24-max** [comment]
Its only happening with easyCredit payment method after getting redirected from easyCredit:
```
SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails 
(`livedb2021`.`sales_order`, CONSTRAINT `SALES_ORDER_CUSTOMER_ID_CUSTOMER_ENTITY_ENTITY_ID` FOREIGN KEY (`customer_id`) REFERENCES `customer_entity` (`entity_id`) ON DELETE SET NULL), query was: INSERT INTO `sales_order` (`state`, `status`, `coupon_code`, `protect_code`, `shipping_description`, `is_virtual`, `store_id`, `customer_id`, `base_discount_amount`, `base_grand_total`, `base_shipping_amount`, `base_shipping_tax_amount`, `base_subtotal`, `base_tax_amount`, `base_to_global_rate`, `base_to_order_rate`, `discount_amount`, `grand_total`, `shipping_amount`, `shipping_tax_amount`, `store_to_base_rate`, `store_to_order_rate`, `subtotal`, `tax_amount`, `total_qty_ordered`, `customer_is_guest`, `customer_note_notify`, `customer_group_id`, `quote_id`, `base_shipping_discount_amount`, `base_subtotal_incl_tax`, `base_total_due`, `shipping_discount_amount`, `subtotal_incl_tax`, `total_due`, `weight`, `customer_dob`, `increment_id`, `applied_rule_ids`, `base_currency_code`, `customer_email`, `customer_firstname`, `customer_lastname`, `customer_middlename`, `customer_prefix`, `customer_suffix`, `customer_taxvat`, `discount_description`, `global_currency_code`, `order_currency_code`, `remote_ip`, `shipping_method`, `store_currency_code`, `store_name`, `x_forwarded_for`, `customer_note`, `total_item_count`, `customer_gender`, `discount_tax_compensation_amount`, `base_discount_tax_compensation_amount`, `shipping_discount_tax_compensation_amount`, `base_shipping_discount_tax_compensation_amnt`, `shipping_incl_tax`, `base_shipping_incl_tax`, `gift_message_id`, `base_cod_fee`, `cod_fee`, `base_cod_tax_amount`, `cod_tax_amount`, `base_cod_fee_incl_tax`, `cod_fee_incl_tax`, `exclude_import_pending`, `exclude_import_complete`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
```

**Comment by netzkollektiv** [comment]
This is most likely not an issue with the extension itself. Please try to disable all third party extension and report back if the issue persists. For any further support regarding your specific system, please send an email to ratenkauf@easycredit.de
