### ISSUE TITLE
Compatibility with Magento 2.4.6

### ISSUE THREAD

**Issue by MTheProgrammer** [teambank/ratenkaufbyeasycredit-plugin-magento-2#12]
Hello,

are there any plans on creating compatibility with Magento 2.4.6 and PHP 8.1+?

The major issue comes from the removal of Zend_* classes in favor of Laminas equivalents.

**Comment by netzkollektiv** [comment]
Hi Matt,

Zend_* classes are not part of the extension anymore since v2.0. Please use the most recent version of the extension which is compatible up to PHP 8.1. An update for PHP 8.2 is coming soon.
