### ISSUE TITLE
Magento default "Ship order" is not going to report the delivery to easyCredit

### ISSUE THREAD

**Issue by p24-max** [teambank/ratenkaufbyeasycredit-plugin-magento-2#13]
Once an order is shipped, our ERP system reports this information to magento2 using REST shipment api.
From magento, the shipment information should then be automatically carried to the payment provider (easyCredit).

This is not working with this easyCredit module as it looks like it does not follow the magento shipment standard. When I do create a shipment (magento default) for an order, easyCredit module is not respecting this. Instead, a custom "report delivery" feature was added by this module which requires manual interaction.

Please wire the magento default order-shipment with the easyCredit report shipment functionality.

**Comment by netzkollektiv** [comment]
The shipment is automatically being sent with the capture action, see here:
https://github.com/teambank/ratenkaufbyeasycredit-plugin-magento-2/blob/4e6e71be349ab3662b29ff78968336ef7d5e7369/Model/Payment.php#L232

This means once you create the invoice for an order the shipment is reported to easyCredit. If this does not suit your workflow you may overwrite the payment model and move the implementation to another action or build a custom observer.

The widget for manual sending is a convenience functionality for merchants who are not using the Magento invoice / shipment system.
