### ISSUE TITLE
Issue on AWS Code Deploy with symlink in docs/ (sphinx_rtd_theme)

### ISSUE THREAD

**Issue by MTheProgrammer** [teambank/ratenkaufbyeasycredit-plugin-magento-2#14]
Hello,

CodeDeploy on AWS fails because of this symlink file that points to not existing target: [sphinx_rtd_theme](https://github.com/teambank/ratenkaufbyeasycredit-plugin-magento-2/blob/main/docs/source/_themes/sphinx_rtd_theme)

![image](https://github.com/teambank/ratenkaufbyeasycredit-plugin-magento-2/assets/6697660/91bd1e89-b023-41e0-a47a-fa3f41d8872b)

Is it really necessary for the docs to be in the same repository as the Magento module? This has impact on our deployment pipeline.

**Comment by netzkollektiv** [comment]
Thanks you for creating the issue. This seems to be a very specific case to me. You may just delete the symlink or the whole directory.

**Comment by MTheProgrammer** [comment]
I'm installing it with composer. I believe that packages pushed to the Packagist repository should contain only the code that is used by the module to reduce download size.

Is it a lot of work from your side to skip the docs directory before publishing it to the registry?

**Comment by netzkollektiv** [comment]
Can you please provide a minimal example how to reproduce the error?
