### ISSUE TITLE
JavaScript loaded even if module disabled or JS not required at this page

### ISSUE THREAD

**Issue by p24-max** [teambank/ratenkaufbyeasycredit-plugin-magento-2#15]
JavaScript is loaded even if ...
1. ... easyCredit is disabled for the store view (e.g. international store views, where easyCredit is not offered)
2. ... it is not used at the page (e.g. main index page, product listing pages, CMS content pages, ...).

![image](https://github.com/teambank/ratenkaufbyeasycredit-plugin-magento-2/assets/106059119/6eedeb3d-ad8a-4665-880f-d0d3befd6ce8)

**Comment by netzkollektiv** [comment]
This is currently the intended behavior as the marketing components and widgets can be used anywhere on the site. 
Though, the behavior can be changed by overwriting the `view/frontend/templates/head/components.phtml` template.
