### ISSUE TITLE
PDP-widget causes CLS (layout shift)

### ISSUE THREAD

**Issue by p24-max** [teambank/ratenkaufbyeasycredit-plugin-magento-2#16]
The easyCredit PDP-Widget causes [CLS](https://web.dev/cls/), see this recording:
<img src="https://github.com/teambank/ratenkaufbyeasycredit-plugin-magento-2/assets/106059119/30e9fd62-63a1-4128-8195-a8a93bb3ed1e" width="400px">

It cant be fixed in theme-CSS because the easyCredit widget DOM element is injected with JavaScript during page load.

**Comment by netzkollektiv** [comment]
Thank you! We are going to review the issue.

You can define a fixed height on the parent element to fix the cls issue.

**Comment by netzkollektiv** [comment]
Thank you ! We will evaluate the integration methods. Currently you could overwrite [view/frontend/templates/easycredit/pp-plugin.phtml](view/frontend/templates/easycredit/pp-plugin.phtml) and adjust the JavaScript in order to wrap the element in a container.
