### ISSUE TITLE
Shipping address is broken when after going back to the Checkout

### ISSUE THREAD

**Issue by ptylek** [teambank/ratenkaufbyeasycredit-plugin-magento-2#2]
**Device:**
all devices

**Steps to reproduce:**
1. Add any product to the Cart.
2. Go to the Checkout-Step 1 and provide proper shipping address (without company), then go to Step 2.
3. Select Easy credit payment method, mark all checkboxes and select Herr/Frau. Then Click on 'Weiter zum Ratenkauf' button.
4. After redirect to Ratenkauf page, go back to the Checkout (using browser back button instead of cancel).

**Expected:**
I am redirected to the Checkout-Step 2. My shipping address is proper.
I can click on 'Weiter zum Ratenkauf' button and go to Ratenkauf page again.

**Actual:**
I am redirected to the Checkout-Step 2. My shipping address is broken.
I can't click on 'Weiter zum Ratenkauf' button again - nothing happens.
Frau/Herr dropdown is missing now.
When I go back to Step 1, then there is no shipping address and no e-mail address provided - nothing.

![image](https://user-images.githubusercontent.com/34317830/147081039-6e0dbfd1-3bbe-4a31-91e9-4187a49af467.png)

**Additional info:**
When in ratenkauf platform, clicking Cancel button redirects back to Cart, but when using browser back button, Checkout is broken.

**Comment by netzkollektiv** [comment]
Thank you @ptylek for creating this issue! We added a fix which will be part of the next extension release.
