### ISSUE TITLE
Infinite loop detected, review the trace for the looping path

### ISSUE THREAD

**Issue by magento360** [teambank/ratenkaufbyeasycredit-plugin-magento-2#9]
0":"Infinite loop detected, review the trace for the looping path","1":"#1 Magento\\Checkout\\Model\\Session\\Interceptor->getQuote() called at [vendor\/teambank\/ratenkaufbyeasycredit-plugin-magento-2\/BackendApi\/Quote.php:33]\n#2 Netzkollektiv\\EasyCredit\\BackendApi\\Quote->__construct() called at 

Module version: "teambank/ratenkaufbyeasycredit-plugin-magento-2": "1.3.9"
magento ver: 2.4.3-p3

**Comment by netzkollektiv** [comment]
This was already resolved with [v1.3.10](https://github.com/teambank/ratenkaufbyeasycredit-plugin-magento-2/releases/tag/1.3.10)
